//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarthquakeQuery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EarthquakeInfo
    {
        public string time { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> depth { get; set; }
        public Nullable<double> mag { get; set; }
        public string magType { get; set; }
        public Nullable<double> nst { get; set; }
        public Nullable<double> gap { get; set; }
        public Nullable<double> dmin { get; set; }
        public Nullable<double> rms { get; set; }
        public string net { get; set; }
        public string id { get; set; }
        public string updated { get; set; }
        public string place { get; set; }
        public string type { get; set; }
        public Nullable<double> horizontalError { get; set; }
        public Nullable<double> depthError { get; set; }
        public Nullable<double> magError { get; set; }
        public Nullable<double> magNst { get; set; }
        public string status { get; set; }
        public string locationSource { get; set; }
        public string magSource { get; set; }
        public int PrimaryKeyID { get; set; }
    }
}
